"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/users/auth.controller");
const basket_controller_1 = require("../controllers/basket/basket.controller");
const delivery_controller_1 = require("../controllers/delivery/delivery.controller");
const products_controller_1 = require("../controllers/products/products.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const router = (0, express_1.Router)();
const authController = new auth_controller_1.AuthController();
const basketController = new basket_controller_1.BasketController();
const deliveryController = new delivery_controller_1.DeliveryController();
const productsController = new products_controller_1.ProductsController();
router.post("/auth/register", authController.register.bind(authController));
router.post("/auth/login", authController.login.bind(authController));
router.post("/auth/logout", auth_middleware_1.authMiddleware, authController.logout.bind(authController));
router.get("/auth/me", auth_middleware_1.authMiddleware, authController.me.bind(authController));
router.get("/basket/active", auth_middleware_1.authMiddleware, basketController.getActive.bind(basketController));
router.post("/basket/items", auth_middleware_1.authMiddleware, basketController.addItem.bind(basketController));
router.get("/delivery/active", auth_middleware_1.authMiddleware, deliveryController.getActive.bind(deliveryController));
router.post("/delivery", auth_middleware_1.authMiddleware, deliveryController.create.bind(deliveryController));
router.get("/products", productsController.list.bind(productsController));
exports.default = router;
